# Generated by Django 6.0.3 on 2026-03-18 06:44

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_code',
            field=models.CharField(default=courses.models.generate_join_code, editable=False, max_length=8, unique=True),
        ),
    ]
