# Generated by Django 6.0.3 on 2026-03-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_join_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='couse',
            new_name='course',
        ),
    ]
